spring:
  datasource:
    url: jdbc:mysql://mysql.grp-arch.svc.cluster.local:3306/sql_workflow?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: gp51@2022
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8080

dolphin:
  baseUrl: http://ds-api.ds.svc.cluster.local:12345/dolphinscheduler
  authToken: 9fffbf2afa33e37eed7588f7e2918826
  project:
    code: 159198460609120L
  tenant:
    code: admin
  max:
    Parallelism: 4
  triggerIntervalSeconds: 300

#monitor:
#  timeoutSeconds: 7200
#  dingWebhook: ${DING_WEBHOOK_URL:}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

openmetadata:
  api:
    url: http://openmetadata-api.grp-arch.svc.cluster.local:8080
postgres:
  url: jdbc:postgresql://188.160.10.19:5432/addax_admin
  username: addax
  password: addax@123

workflow:
  schedule:
    triggerPending: "0/15 * 9-23,0-7 * * ?"
    checkRunning: "0/15 * 9-23,0-7 * * ?"
    initialize: "0 0 09 * * ?"
