spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sql_workflow?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: xiao@duan712
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#  flyway:
#    enabled: true
#    locations: classpath:db/migration
server:
  port: 9000

dolphin:
  baseUrl: https://ds.gp51.com/dolphinscheduler
  authToken: 28459a89b01e79187adeb206334d0abd
  project:
    code: 159198460609120L
  tenant:
    code: admin
  max:
    Parallelism: 4
  triggerIntervalSeconds: 300

monitor:
  timeoutSeconds: 7200
  dingWebhook: ${DING_WEBHOOK_URL:}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

openmetadata:
  api:
#    url: http://openmetadata-api.grp-arch.svc.cluster.local:8080
    url: http://localhost:8080/api/lineage

postgres:
  url: jdbc:postgresql://127.0.0.1:5432/addax_admin
  username: addax
  password: addax@123
